import { Router } from 'express';
import mongoose from 'mongoose';
import { generateModelPdf, assertValidAnalysis } from '../services/modelService.js';
import { requireAuth } from '../middleware/auth.js';
import { assert } from '../middleware/validate.js';
import { Assessment } from '../db/models/Assessment.js';

const router = Router();

/**
 * Resolves the `analysis` object for a PDF request. Two ways to provide it:
 *  - `analysis` directly in the body — no auth required, exactly the
 *    original stateless proxy behavior (unchanged, still fully anonymous).
 *  - `userId` + `assessmentId` instead — looks up that assessment's stored
 *    report_json so the caller never has to re-paste it. This path DOES
 *    require a valid Bearer token for that same user (or an admin) — it's
 *    reading a specific person's cognitive assessment data, so unlike the
 *    analysis-direct path it can't be anonymous.
 *
 * Returns: the resolved analysis object, `undefined` if neither analysis
 * nor userId/assessmentId were given (caller should fall through to the
 * normal "analysis is required" validation), or `null` if an error
 * response has already been sent (auth/ownership/not-found).
 */
async function resolveAnalysis(req, res, bodyAnalysis) {
  if (bodyAnalysis !== undefined) return bodyAnalysis;

  const { userId, assessmentId } = req.body || {};
  if (!userId && !assessmentId) return undefined;

  assert(
    userId && mongoose.isValidObjectId(userId),
    'userId must be a valid id when assessmentId is used instead of analysis',
    ['userId']
  );
  assert(assessmentId && mongoose.isValidObjectId(assessmentId), 'assessmentId must be a valid id', ['assessmentId']);

  let authorized = false;
  await new Promise((resolve) => {
    requireAuth(req, res, () => {
      authorized = true;
      resolve();
    });
    if (res.headersSent) resolve(); // requireAuth already sent a 401
  });
  if (!authorized) return null;

  if (req.auth.role !== 'admin' && req.auth.userId !== userId) {
    res.status(403).json({ error: 'You can only access your own data' });
    return null;
  }

  const assessment = await Assessment.findOne({ _id: assessmentId, user_id: userId });
  if (!assessment) {
    res.status(404).json({ error: 'Assessment not found for this user' });
    return null;
  }
  return assessment.report_json;
}

const sendPdf = async (res, analysis, brand, teaser) => {
  let buffer;
  try {
    buffer = await generateModelPdf(analysis, brand, { teaser });
  } catch (err) {
    console.error(`[pdf] ${teaser ? 'teaser' : 'full'} PDF generation failed:`, err.message);

    // Surface a helpful error instead of a generic 500
    const isUnreachable = /could not reach|ECONNREFUSED|ENOTFOUND|timeout/i.test(err.message);
    const status = isUnreachable ? 502 : 500;
    return res.status(status).json({
      error: isUnreachable
        ? 'The report generation service is currently unreachable. Please try again later.'
        : 'PDF generation failed. Make sure the "analysis" body is the full, unmodified object returned by /api/v1/analyze.',
      detail: err.message,
    });
  }

  const fileName = teaser
    ? `Limitless_Cognitive_Teaser_${new Date().toISOString().split('T')[0]}.pdf`
    : `Limitless_Cognitive_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  res
    .status(200)
    .set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Content-Length': buffer.length,
    })
    .send(buffer);
};

/**
 * POST /api/v1/generate-pdf
 * Body: EITHER { analysis: <report JSON>, brand? } — anonymous, unchanged —
 *       OR     { userId, assessmentId, brand? } — requires a Bearer token
 *              for that user (or admin); uses the assessment's stored
 *              report_json instead of resending it.
 * Response: application/pdf (full report, generated by the AI model service)
 */
router.post('/generate-pdf', async (req, res) => {
  const { analysis: bodyAnalysis, brand } = req.body || {};
  const analysis = await resolveAnalysis(req, res, bodyAnalysis);
  if (analysis === null) return; // error response already sent
  assertValidAnalysis(analysis);
  await sendPdf(res, analysis, brand, false);
});

/**
 * POST /api/v1/generate-teaser-pdf
 * Body: EITHER { analysis: <report JSON>, brand? } — anonymous, unchanged —
 *       OR     { userId, assessmentId, brand? } — requires a Bearer token
 *              for that user (or admin); uses the assessment's stored
 *              report_json instead of resending it.
 * Response: application/pdf (free preview with locked sections)
 */
router.post('/generate-teaser-pdf', async (req, res) => {
  const { analysis: bodyAnalysis, brand } = req.body || {};
  const analysis = await resolveAnalysis(req, res, bodyAnalysis);
  if (analysis === null) return; // error response already sent
  assertValidAnalysis(analysis);
  await sendPdf(res, analysis, brand, true);
});

export default router;
