import { Router } from 'express';
import { generateModelPdf, assertValidAnalysis } from '../services/modelService.js';

const router = Router();

const sendPdf = async (res, analysis, brand, teaser) => {
  let buffer;
  try {
    buffer = await generateModelPdf(analysis, brand, { teaser });
  } catch (err) {
    console.error(`[pdf] ${teaser ? 'teaser' : 'full'} PDF generation failed:`, err.message);

    // Surface a helpful error instead of a generic 500
    const isUnreachable = /could not reach|ECONNREFUSED|ENOTFOUND|timeout/i.test(err.message);
    const status = isUnreachable ? 502 : 500;
    return res.status(status).json({
      error: isUnreachable
        ? 'The report generation service is currently unreachable. Please try again later.'
        : 'PDF generation failed. Make sure the "analysis" body is the full, unmodified object returned by /api/v1/analyze.',
      detail: err.message,
    });
  }

  const fileName = teaser
    ? `Limitless_Cognitive_Teaser_${new Date().toISOString().split('T')[0]}.pdf`
    : `Limitless_Cognitive_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  res
    .status(200)
    .set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Content-Length': buffer.length,
    })
    .send(buffer);
};

/**
 * POST /api/v1/generate-pdf
 * Body: { analysis: <report JSON>, brand?: { primaryColor, accentColor } }
 * Response: application/pdf (full report, generated by the AI model service)
 */
router.post('/generate-pdf', async (req, res) => {
  const { analysis, brand } = req.body || {};
  assertValidAnalysis(analysis);
  await sendPdf(res, analysis, brand, false);
});

/**
 * POST /api/v1/generate-teaser-pdf
 * Body: { analysis: <report JSON>, brand?: {...} }
 * Response: application/pdf (free preview with locked sections)
 */
router.post('/generate-teaser-pdf', async (req, res) => {
  const { analysis, brand } = req.body || {};
  assertValidAnalysis(analysis);
  await sendPdf(res, analysis, brand, true);
});

export default router;
